### ISSUE TITLE
Erro de vazamento da tela de login

### ISSUE THREAD

**Issue by johelo** [fiap-winners/trustacademy-mobile#3]
No log do Android Studio aparece essa mensagem:

E/WindowManager: android.view.WindowLeaked: Activity com.fiap.trustacademy.LoginActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3d8ddbf7 G.E..... R.....ID 0,0-1368,406} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:298)
        at com.fiap.trustacademy.LoginActivity.loginUser(LoginActivity.kt:72)
        at com.fiap.trustacademy.LoginActivity.access$loginUser(LoginActivity.kt:16)
        at com.fiap.trustacademy.LoginActivity$initialise$1.onClick(LoginActivity.kt:51)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by leocristofani** [comment]
Fixed
